### ISSUE TITLE
omniauth-oauth2 dependency version is incompatible with other strategies dependencies

### ISSUE THREAD

**Issue by khier996** [jclusso/omniauth-linkedin-openid#1]
First of all thanks @jclusso for this gem.
I wanted to just swap this gem with the old `omniauth-linkedin-oauth2` like you mentioned [here](https://github.com/decioferreira/omniauth-linkedin-oauth2/pull/77#issuecomment-1715784819), but for us the problem is that we use gems for other strategies and they all lock `omniauth-oauth2` dependency to `1.7.x` versions. In this gem it is locked to `1.8.0`, which creates a conflict `Could not find compatible versions`. 
I checked https://github.com/omniauth/omniauth-oauth2 and the latest release is `1.7.3`. Is there a reason you locked to the version `1.8.0`? Can we use `1.7.3` instead?

**Comment by jclusso** [comment]
I don't have a reason for locking it to that. We can lower the required version if everything works.

**Comment by jclusso** [comment]
@khier996 I was looking into this and when looking at a lot of the other OmniAuth strategy gems they all appear to have this set to 1.8. Is there a reason you can't upgrade `omniauth-oauth2` to 1.8.0. I don't know why they have 1.7.3 set as the latest, but 1.8.0 is the actual highest release version, release a day before 1.7.3.

See all of these gems that use 1.8:

- [omniauth-github](https://github.com/omniauth/omniauth-github/blob/f27bb4e018150d87e9444ad13955acfc9e76f4d7/omniauth-github.gemspec#L20)
- [omniauth-azure-activedirectory-v2](https://github.com/RIPAGlobal/omniauth-azure-activedirectory-v2/blob/d0b1739e1f4e263d74350b6d53b6a3e3cbcefd9e/omniauth-azure-activedirectory-v2.gemspec#L48)
- [omniauth-google-oauth2](https://github.com/zquestz/omniauth-google-oauth2/blob/2f8cefd7ef9701e92b7ee227073fb5f85c847817/omniauth-google-oauth2.gemspec#L26)

**Comment by khier996** [comment]
Sorry, I shouldn't have said `all`. Some of them lock to lower versions. 
[omniauth-microsoft_graph](https://github.com/synth/omniauth-microsoft_graph) used to be locked to `1.7.x` version, but I see it was upgraded recently. So, I think it should be ok to upgrade in our codebase too.
The last problematic one is [omniauth-amazon](https://github.com/wingrunr21/omniauth-amazon). It hasn't been updated in a long time. I actually even had to [fork it](https://github.com/khier996/omniauth-amazon) and upgrade `omniauth-oauth2` to `~> 1.7.1` to make it work with other libraries. I just tried to upgrade my fork to `1.8` but it results in an error. 
I think for now I'll just use the [fork](https://github.com/khier996/omniauth-linkedin-openid/blob/master/omniauth-linkedin-openid.gemspec) of your library with the downgraded `omniauth-oauth2` version.

**Comment by jclusso** [comment]
@khier996 that makes the most sense I think. Going to close this for now.
