### ISSUE TITLE
"Duplicate values defined" error

### ISSUE THREAD

**Issue by khier996** [jclusso/omniauth-linkedin-openid#2]
My code used to work with the old [omniauth-linkedin-oauth2](https://github.com/decioferreira/omniauth-linkedin-oauth2) gem.
Then I swapped the gem with this one, like suggested [here](https://github.com/decioferreira/omniauth-linkedin-oauth2).
It results in this error:
`{"error":"invalid_request","error_description":"Duplicate values defined for \"client_secret\" parameter"}`
Do you know what might be causing it?

**Comment by jclusso** [comment]
@khier996 I'm not sure what would cause that. Did you update your LinkedIn application to have the proper products? Without seeing your configuration and what not, I don't really have an idea what could be causing it.

**Comment by antonioJASR** [comment]
Hello @khier996 . Can you provided a code example to reproduce the error? I tried but I wasn't able to get that error.

**Comment by frenkel** [comment]
Same problem here with a newly created LinkedIn app. In the old gem it seems this was a fix for that same problem:
https://github.com/decioferreira/omniauth-linkedin-oauth2/pull/71

**Comment by jclusso** [comment]
My app was newly creaed when I made this. Can you put togather an example app that is broken. I don't know how to currently recreate this.

**Comment by jclusso** [comment]
I'm using devise as well and I think the issue is the documentation is wrong. Try this.

```ruby
config.omniauth :linkedin,
  client_id: ENV['LINKEDIN_CLIENT_ID'],
  client_secret: ENV['LINKEDIN_CLIENT_SECRET']
```

**Comment by frenkel** [comment]
No, that doesn't solve the problem. Removing this method does solve it though: https://github.com/jclusso/omniauth-linkedin-openid/blob/master/lib/omniauth/strategies/linkedin.rb#L80

It was added in the original gem by this PR: https://github.com/decioferreira/omniauth-linkedin-oauth2/pull/71

**Comment by jclusso** [comment]
Hmmm,  I'm just lost how it would work for me. What version of devise and oauth2? I'm on 4.8.1 and 2.0.4 respectively. I don't want to just remove that method without understanding how it works for some, but not all.
