### ISSUE TITLE
Successful authentication results in `REVOKED_ACCESS_TOKEN` error

### ISSUE THREAD

**Issue by BSierakowski** [jclusso/omniauth-linkedin-openid#6]
Hey Jarrett :).

Pretty frequently when I successfully authenticate with LinkedIn I get the following error back:

{
  "status":401,
  "serviceErrorCode":65601,
  "code":"REVOKED_ACCESS_TOKEN",
  "message":"The token used in the request has been revoked by the user"
}

I'm pretty confident that authenticating is working because the app shows up as a "permitted service" authed with the correct scopes even after getting the error back.

I did a bit of digging and I saw some people saying that after linkedin generates the token it takes a bit for the token to become active, and we obviously try to create our token right after, which is where I'm guessing the problem happens.

Have you seen this before and thought of any work around, or is this a me thing?

**Comment by jclusso** [comment]
Hi @BSierakowski, I can't say I have. Are you sure you enabled all of the scopes on your LinkedIn app?

**Comment by BSierakowski** [comment]
I think so, but I'll triple check. I'm asking for `openid profile email w_member_social`, and I see the following granted permissions:

```
You have granted the following access to the service:
- Use the primary email address associated with your LinkedIn account
- Use your name and photo
- Create, modify, and delete posts, comments, and reactions on your behalf
```

I'm also getting the error back right after authentication, so it's not like I'm making a follow up request and getting unauthorized due to a missing scope (I think I've also done that and the error message is specific.)

If this is new to you I can mess around with it and figure out—very likely that I'm messing up something unrelated :).

**Comment by jclusso** [comment]
Well let me know if you find anything. Happy to accept PRs or work to resolve together.

**Comment by BSierakowski** [comment]
If I'm stuck for more than a week I'll come crawling back for help 😅

**Comment by batalla3692** [comment]
Same over here... I found out that the LinkedIn SSO login in my production environment has been very flaky last couple of days _(we still use the [old gem](https://github.com/decioferreira/omniauth-linkedin-oauth2) for that integration)_, and after creating a fresh new app on LinkedIn and setting up this gem I get the same `REVOKED_ACCESS_TOKEN` 90% of the time in my local.

**Comment by batalla3692** [comment]
This doesn't seem to be related to this particular gem. The [deprecated gem](https://github.com/decioferreira/omniauth-linkedin-oauth2) with the previous LinkedIn strategy [has an open issue](https://github.com/decioferreira/omniauth-linkedin-oauth2/issues/17) from 2014 with the very same problem that is still active, and it looks like a problem with the LinkedIn API itself.

There are some possible solutions there as well. Hope this help anyone ✌️

**Comment by garrywilliams** [comment]
Thanks @batalla3692, that helps. This started happening for us when we created a new token on LinkedIn and I had assumed it was a config issue at our end.

**Comment by jclusso** [comment]
Fixed and released in https://github.com/jclusso/omniauth-linkedin-openid/releases/tag/1.0.2

**Comment by BSierakowski** [comment]
@batalla3692 the goat!! Thank you :).
